### ISSUE TITLE
CurseForge

### ISSUE THREAD

**Issue by litjohn50** [stfwi/wilescollection#1]
Why don't you have an issues tab on the CurseForge frontpage to bring people to this issues sections?

**Comment by stfwi** [comment]
Hi, the main issue tracker link (to here on the hub) is in the meta data of the mod itself. The mod page on Curse needs some updating in general. Having that said - as the mod is not much used, there is not really a major point in doing that, is it?  ;)

**Comment by stfwi** [comment]
Tracker link is setup on Curse. Cheers ;;
